export type TicketCategory =
  | 'aircon'
  | 'electrical'
  | 'plumbing'
  | 'furniture'
  | 'internet'
  | 'pest'
  | 'other'

export type TicketStatus =
  | 'submitted'
  | 'assigned'
  | 'in_progress'
  | 'resolved'
  | 'cancelled'

export interface MaintenanceTicket {
  id: string
  /** Human-friendly reference like TK-0001, generated by the database. */
  code?: string
  category: TicketCategory
  title: string
  description: string
  status: TicketStatus
  scheduled_at?: string
  technician_name?: string
  rating?: number
  rating_comment?: string
  is_scheduled_service?: boolean
  created_at: string
  updated_at: string
  timeline: { stage: TicketStatus; at: string; note?: string }[]
}
